// Supplemental diagnostics: adjacent representable states and the saved right endpoint.
#define OBS32_SUPPORT_ONLY
#include "obs32_forensics.cpp"
int main(int argc,char**argv){try{
 using namespace Probe;gsl_set_error_handler_off();std::cout<<std::setprecision(17)<<std::unitbuf;
 require(argc==11,"profile certificate thermal work entry frozen coefficients cases primary-output output");Inputs in;in.profile=argv[1];in.certificate=argv[2];in.thermal=argv[3];in.work=argv[4];in.entry=argv[5];in.frozen=argv[6];in.coefficients=argv[7];in.output=argv[10];require(!std::filesystem::exists(in.work)&&!std::filesystem::exists(in.output),"fresh supplemental directories");std::filesystem::create_directories(in.output);
 auto c=ReadCases(argv[8]).front();std::ifstream solutions(std::filesystem::path(argv[9])/"solutions.tsv");std::string line;std::getline(solutions,line);std::map<std::string,std::vector<std::string>> saved;while(std::getline(solutions,line)){auto v=Split(line);saved[v.at(0)]=v;}
 auto load=[&](std::string key){const auto&v=saved.at(key);return State{{std::stod(v[5]),std::stod(v[6]),std::stod(v[7])}};};
 const double tk=std::stod(saved.at("split-left-O3")[4]);require(tk>c.left&&tk<c.obs,"event time bounds");auto began=Clock::now();auto physics=BuildContext(in);physics->RequireFullCurrent();auto ctx=physics->OrdinaryContext()->DriverContext();ActualCheckpointContext initial(physics,1);State temp;initial.Derivative(tk,load("split-left-O3"),temp);const auto&cache=Cache(*ctx.star);double knot=cache.Tinf_MeV[95];
 double x0=std::log(knot/RC::BoltzmannMeVPerK/1e8),xm=x0,xp=x0,at=x0;bool exact=TM(x0)==knot;for(int i=0;i<128&&!exact;++i){xm=std::nextafter(xm,-INFINITY);xp=std::nextafter(xp,INFINITY);if(TM(xm)==knot){at=xm;exact=true;}else if(TM(xp)==knot){at=xp;exact=true;}}
 double below=at,above=at;for(int i=0;i<2048&&TM(below)>=knot;++i)below=std::nextafter(below,-INFINITY);for(int i=0;i<2048&&TM(above)<=knot;++i)above=std::nextafter(above,INFINITY);require(TM(below)<knot&&TM(above)>knot,"adjacent knot bracketing");
 std::ofstream out(in.output/"adjacent-rhs.tsv");out<<std::setprecision(17)<<"warm_side\tpoint\texact_knot_representable\tx\tT_MeV\tT_K\tcell\txdot\teta_dot_e\teta_dot_mu\tCstar\tPnet\tPdir\tLH\tDeltaLnu\tLnu_eq\tLnu_full\tLgamma\tsigma_e\tsigma_mu\tR_e\tR_mu\n";
 for(int side:{-1,1})for(auto entry:std::vector<std::pair<std::string,double>>{{"below",below},{"at",at},{"above",above}}){ctx.star->HeatCapacityStar_Tinf(cache.Tinf_MeV[95+side],*ctx.thermo,ctx.geo);ActualCheckpointContext isolated(physics,2);State y=load("split-left-O3"),dy;y[0]=entry.second;isolated.Derivative(tk,y,dy);auto d=isolated.EvaluateDiagnostics(tk,y);out<<side<<'\t'<<entry.first<<'\t'<<exact<<'\t'<<y[0]<<'\t'<<TM(y[0])<<'\t'<<d.Tinf_K<<'\t'<<Cache(*ctx.star).last_i;StateLine(out,dy);out<<'\t'<<d.Cstar_erg_K<<'\t'<<d.Pnet_erg_s<<'\t'<<d.P_dir_actual_erg_s<<'\t'<<d.LH_erg_s<<'\t'<<d.DeltaLnu_erg_s<<'\t'<<d.Lnu_eq_erg_s<<'\t'<<d.Lnu_full_erg_s<<'\t'<<d.Lgamma_erg_s<<'\t'<<d.sigma_count_s[0]<<'\t'<<d.sigma_count_s[1]<<'\t'<<d.R_count_s[0]<<'\t'<<d.R_count_s[1]<<'\n';}
 out.close();std::cout<<"ADJACENT_STATE_AUDIT exact_knot_representable "<<exact<<'\n';
 Lab lab(physics,in.output);auto a=lab.Solve("right-endpoint-rk8pd-O3",gsl_odeiv2_step_rk8pd,3,tk,c.right,load("split-left-O3"));auto b=lab.Solve("right-endpoint-rkf45-O3",gsl_odeiv2_step_rkf45,3,tk,c.right,load("independent-left-O3"));require(a.rc==0&&b.rc==0,"right endpoint replay status");
 std::ofstream final(in.output/"main-step-comparison.tsv");final<<std::setprecision(17)<<"component\tmain_right\trk8pd_right\trkf45_right\tmain_minus_rk8pd\tmethod_difference\n";for(int i=0;i<3;++i)final<<i<<'\t'<<c.yr[i]<<'\t'<<a.y[i]<<'\t'<<b.y[i]<<'\t'<<c.yr[i]-a.y[i]<<'\t'<<a.y[i]-b.y[i]<<'\n';physics->RequireFullCurrent();std::ofstream done(in.output/"completion.tsv");done<<std::setprecision(17)<<"key\tvalue\nnew_local_legs\t2\nfull_trajectories\t0\nwall_s\t"<<std::chrono::duration<double>(Clock::now()-began).count()<<'\n';std::cout<<"SUPPLEMENT_COMPLETE\n";return 0;
 }catch(const std::exception&e){std::cerr<<"STOP "<<e.what()<<'\n';return 1;}}
